version: '3'
services:
  db:
    restart: unless-stopped
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  flask:
    image: webapp-flask
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./app:/app"
    tty: true
    depends_on:
      - db

volumes:
  db_data:
