version: '3'
services:
  flask:
    image: webapp-flask
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./app:/app"
    tty: true

  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - flask