version: '3'
services:
  db:
    restart: unless-stopped
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  flask:
    image: webapp-flask
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./app:/app"
    tty: true
    depends_on:
      - db

  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - flask

volumes:
  db_data:
