version: '3'
services:

  db:
    restart: unless-stopped
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  flask:
    image: webapp-flask
#    command: ["/app/init-prod.sh"]
    environment:
      - APP_SETTINGS=flask_app.config.ProductionConfig
      
  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - flask
