version: '3'
services:
  flask:
    command: ["/app/init-prod.sh"]
  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - flask
