version: '3'
services:
  
  db:
    restart: unless-stopped
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  flask:
    environment:
      - APP_SETTINGS=flask_app.config.DevelopmentConfig
